/* Demo catalog — static data for manual testing */
window.SHOP_PRODUCTS = [
  {
    id: "p1",
    name: "Wireless Earbuds Pro",
    category: "Electronics",
    price: 79.99,
    sku: "SN-EAR-001",
    emoji: "🎧",
  },
  {
    id: "p2",
    name: "Stainless Steel Water Bottle",
    category: "Lifestyle",
    price: 24.5,
    sku: "SN-BTL-042",
    emoji: "🧴",
  },
  {
    id: "p3",
    name: "USB-C Hub 7-in-1",
    category: "Electronics",
    price: 45.0,
    sku: "SN-HUB-007",
    emoji: "🔌",
  },
  {
    id: "p4",
    name: "Cotton Crew T-Shirt",
    category: "Apparel",
    price: 18.99,
    sku: "SN-TS-100",
    emoji: "👕",
  },
  {
    id: "p5",
    name: "Desk Lamp LED",
    category: "Home",
    price: 36.0,
    sku: "SN-LMP-03",
    emoji: "💡",
  },
  {
    id: "p6",
    name: "Running Shoes Lite",
    category: "Apparel",
    price: 89.0,
    sku: "SN-SHO-22",
    emoji: "👟",
  },
  {
    id: "p7",
    name: "Yoga Mat 6mm",
    category: "Lifestyle",
    price: 32.25,
    sku: "SN-YGA-06",
    emoji: "🧘",
  },
  {
    id: "p8",
    name: "Portable Phone Stand",
    category: "Electronics",
    price: 12.49,
    sku: "SN-STN-01",
    emoji: "📱",
  },
];
